options:
  calico-node-image:
    type: string
    # Please refer to layer-canal/versioning.md before changing the version below.
    default: docker.io/calico/node:v3.6.1
    description: |
      The image id to use for calico/node.
  calico-policy-image:
    type: string
    default: docker.io/calico/kube-controllers:v3.6.1
    description: |
      The image id to use for calico/kube-controllers.
  ipip:
    type: string
    default: Never
    description: |
      IPIP mode. Must be one of "Always", "CrossSubnet", or "Never".
  nat-outgoing:
    type: boolean
    default: true
    description: |
      NAT outgoing traffic
  cidr:
    type: string
    default: "192.168.0.0/16"
    description: |
      Network CIDR assigned to Calico. This is applied to the default Calico
      pool, and is also communicated to the Kubernetes charms for use in
      kube-proxy configuration.
